routing:

  admin_shopsettings_list:
    path: ^\/admin\/shopsettings\/list\/?$
    isSecure: 1
    i18n: 1
    controller: shopsettings/backend/shopsettings_list
  admin_shopsettings_edit:
    path: ^\/admin\/shopsettings\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: shopsettings/backend/shopsettings_edit
  admin_shopsettings_create:
    path: ^\/admin\/shopsettings\/create\/?$
    isSecure: 1
    i18n: 1
    controller: shopsettings/backend/shopsettings_create
  admin_shopsettings_delete:
    path: ^\/admin\/shopsettings\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: shopsettings/backend/shopsettings_delete