shopsettings:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    user_id: INT NOT NULL
    shop_name: VARCHAR(255)
    shop_introduction: TEXT
    shop_announcement: TEXT
    shop_logo: VARCHAR(255)
    shop_wechat: VARCHAR(25)
    shop_phone: VARCHAR(15)
    shop_address: VARCHAR(512)
    shop_email: VARCHAR(32)
    stripe_public_key: VARCHAR(48)
    stripe_private_key: VARCHAR(80)
    stripe_uid: VARCHAR(32)
  fks:
    user_id:
      foreign_key: user_id
      references: site_user.id
      on_delete: CASCADE
      on_update: CASCADE
  form:
    fields:
      shop_logo:
        widget: plupfile
        widget_conf:
          required: 0
          upload_dir: files/user
          # max_file_size in mb
          max_file_size: 4
          max_file_number: 1
          extensions: jpg,png,gif,jpeg
          transform:
            dimension: 350x350
#            refill: "0,0,0"
#            watermark: modules/site/assets/images/favicon.png
      shop_wechat:
        widget: text
        widget_conf:
          required: 0
      shop_phone:
        widget: text
        widget_conf:
          required: 0
      shop_address:
        widget: textarea
        widget_conf:
          required: 0
          wysiwyg: 0
#          wysiwyg_toolbar: standard
      shop_email:
        widget: text
        widget_conf:
          required: 0
    names:
      en: Shop settings
      zh: 微店设置