shopsettings:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    user_id: INT NOT NULL
    shop_name: VARCHAR(255)
    shop_introduction: TEXT
    shop_announcement: TEXT
    shop_logo: VARCHAR(255)
    stripe_public_key: VARCHAR(48)
    stripe_private_key: VARCHAR(48)
  fks:
    user_id:
      foreign_key: user_id
      references: site_user.id
      on_delete: CASCADE
      on_update: CASCADE
  form:
    fields:
      shop_logo:
        widget: plupfile
        widget_conf:
          required: 0
          upload_dir: files/user
          # max_file_size in mb
          max_file_size: 4
          max_file_number: 1
          extensions: jpg,png,gif,jpeg
          transform:
            dimension: 80x80
#            refill: "0,0,0"
#            watermark: modules/site/assets/images/favicon.png
    names:
      en: Shop settings
      zh: 微店设置