product:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    user_id: INT NOT NULL
    title: VARCHAR(512) NOT NULL
    thumbnail: VARCHAR(256)
    description: TEXT
    price: VARCHAR(10) NOT NULL
    original_price: VARCHAR(10)
    onshelf: TINYINT(1) DEFAULT 1
    sales: INT DEFAULT 0
    stock: INT DEFAULT 0
    created_at: INT
  fks:
    user_id:
      foreign_key: user_id
      references: site_user.id
      on_delete: CASCADE
      on_update: CASCADE

  form:
    fields:
      title:
        widget: text
        widget_conf:
          required: 1
      thumbnail:
        widget: plupfile
        widget_conf:
          required: 0
          upload_dir: files/user/1
          # max_file_size in mb
          max_file_size: 4
          max_file_number: 8
          extensions: jpg,png,gif
          transform:
            dimension: 414x414
            refill: "255,255,255"
#            watermark: modules/user/assets/images/test.png
      description:
        widget: textarea
        widget_conf:
          required: 1
          wysiwyg: 0
      price:
        widget: text
        widget_conf:
          required: 1
      stock:
        widget: text
        widget_conf:
          required: 0
      onshelf:
        widget: checkbox_single
        widget_conf: 
    names:
      en: Product
      zh: 产品