mail:
  # conf for email sending to amdin
  admin:
    to: george@ct21.com.au
#    to: jeffreycaizhenyuan@gmail.com
    from: jeffreycaizhenyuan@gmail.com
    mailer: smtp
    SMTPSecure: tls
    host: smtp.mandrillapp.com
    port: 587
    username: HFDT0EEMN12bj5yM2EDQ2gTMsJXan5WYlp2T
    nickname: ct21 website
    password: GRTQpVjb3cmZtkVWJFXTyFFNitUOYhnWqBzdIJGN
    
  ticket:
    from: ozboxoffice@gmail.com
    mailer: smtp
    SMTPSecure: tls
    host: smtp.mandrillapp.com
    port: 587
    username: HFDT0EEMN12bj5yM2EDQ2gTMsJXan5WYlp2T
    password: GRTQpVjb3cmZtkVWJFXTyFFNitUOYhnWqBzdIJGN