routing:
  index:
    path: ^\/?$
    isSecure: 0
    i18n: 0
    controller: site/index
  signup:
    path: ^\/signup\/?$
    isSecure: 0
    i18n: 0
    controller: site/signup
  signin:
    path: ^\/signin\/?$
    isSecure: 0
    i18n: 0
    controller: site/signin
  terms:
    path: ^\/terms\/?$
    isSecure: 0
    i18n: 0
    controller: site/terms
  user:
    path: ^\/user\/?$
    isSecure: 0
    i18n: 0
    controller: user/index
  shop:
    path: ^\/shop\/([^\/]+)\/?$
    isSecure: 0
    i18n: 0
#    controller: theme_weidian/index
    controller: theme_default/index
  contact:
    path: ^\/shop\/([^\/]+)\/contact\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/contact
  product:
    path: ^\/shop\/([^\/]+)\/(\d+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/product
  cart_add:
    path: ^\/shop\/([^\/]+)\/cart\-add\/(\d+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/cart_add
  checkout:
    path: ^\/shop\/([^\/]+)\/checkout\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/checkout
  order_confirm:
    path: ^\/order\/confirm\/([^\/]+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/order_confirm
  order_confirmed:
    path: ^\/order\/confirmed\/([^\/]+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/order_confirmed
  order_payment:
    path: ^\/order\/payment\/([^\/]+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/order_payment
  order_paid:
    path: ^\/order\/paid\/([^\/]+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/order_paid
  order_payment_confirmed:
    path: ^\/order\/payment_confirmed\/([^\/]+)\/?$
    isSecure: 0
    i18n: 0
    controller: theme_default/order_payment_confirmed

assets:
  frontend:
    css:
      bootstrap:
        path: .?
        position: top
        weight: 10
        source: //maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
      fontawesome:
        path: .?
        position: top
        weight: 20
        source: https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
      owlcarousel:
        path: .?
        position: top
        weight: 30
        source: ../../libraries/owlcarousel/assets/owl.carousel.css
      owlcarousel_theme:
        path: .?
        position: top
        weight: 30
        source: ../../libraries/owlcarousel/assets/owl.theme.default.css
      sweet_alert:
        path: .?
        position: top
        weight: 40
        source: ../../libraries/bootstrap-sweetalert/lib/sweet-alert.css
      
      site:
        path: .?
        position: top
        weight: 40
        source: site/assets/css/style.css
        
    js:
      bootstrap:
        path: .?
        position: bottom
        weight: 10
        source: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js
      owlcarousel:
        path: .?
        position: bottom
        weight: 20
        source: ../../libraries/owlcarousel/owl.carousel.min.js
      sweet_alert:
        path: .?
        position: bottom
        weight: 40
        source: ../../libraries/bootstrap-sweetalert/lib/sweet-alert.min.js
        
#      site:
#        path: .?
#        position: bottom
#        weight: 30
#        source: site/assets/js/script.js
