sitename: 松果澳洲在线电子商务平台
sitename_short: 松果电商
siteemail: songguo.com.au@gmail.com

demo_account: demo

admin_stripe_secret_key_dev: 1IzM==QMZdVOV9WS1lDU01GRHdGVGN2Z5J3aWZWarFTOfR3clR3XrNXS
admin_stripe_public_key_dev: WBDO==gYEJHczR2Q0MHbhFUY5kGWEN1YMVESDBjZkVndfR3clR3XrBXV
admin_stripe_secret_key_prod: 0FFT==QNIJTTLNzbTR1NatEO5hkTR52TJlHZNhUQFhDafVmdpx2XrNHc
admin_stripe_public_key_prod: IRlZ==wYldlWEJnc1NTbJV3ZX1GVCRmdZd3ZV1WZBhjdfVmdpx2XrBXY

member:
  NORMAL:
    product_limit: 5
    name: 普通会员
    setup_fee: 0
    transaction_fee: 0
  GOLD:
    product_limit: 25
    name: 黄金会员
    setup_fee: 22.22
    transaction_fee: 0.22
  PLATINUM:
    product_limit: 999999
    name: 白金会员
    setup_fee: 22.22
    transaction_fee: 0.36
  SELF:
    product_limit: 99999
    name: 内部会员
    transaction_fee: 0
    setup_fee: 0

demo_accounts:
  - aixin
  - foodking
  
promoted_shops:
  - dummy