sitename: 松果澳洲在线电子商务平台
sitename_short: 松果电商
siteemail: songguo.com.au@gmail.com


member:
  NORMAL:
    product_limit: 5
  GOLD:
    product_limit: 25
  PLATINUM:
    product_limit: 999999

