charge_item:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    title: VARCHAR(256)
    reference: VARCHAR(256)
    amount: VARCHAR(5)
    created_at: INT
    charged: TINYINT DEFAULT 0